version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      FLASK_ENV: development
      DB_HOST: mysql.reto-ucu.net
      DB_PORT: 50006
      DB_USER: xr_g6_admin
      DB_PASSWORD: Bd2025!
      DB_NAME: XR_Grupo6
      FLASK_APP: app.py
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
